[tool.black]
line-length = 88
target-version = ["py38"]

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.ruff]
line-length = 88
per-file-ignores = {"settings/production.py" = ["F401", "F405"]}
