name: Tests

on:
  push:
    branches: 
      - main
      
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run
          start: npm start
      - name: Jest run
        uses: npm test
